<div class="container">
    <h1 class="text-center mb-4">Vínculos</h1>
    <div class="text-right mb-3">
        <button class="btn btn-success" onclick="window.location.href='/vinculos/save'">Criar Novo Vínculo</button>
    </div>
    <table class="table table-bordered">
        <thead class="thead-dark">
            <tr>
                <th>Veículo</th>
                <th>Motorista</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->bonds as $bond): ?>
                <tr>
                    <td><?php echo "({$bond['placa']}) - {$bond['marca']} {$bond['modelo']}" ?></td>
                    <td><?php echo "({$bond['cpf']}) - {$bond['nome']}" ?></td>
                    <td class="d-flex justify-content-center">
                        <button class="btn btn-danger btn-sm mr-2 delete" data-placa="<?php echo $bond['placa'] ?>" data-cpf="<?php echo $bond['cpf'] ?>" href="/vinculos/delete">Deletar</button>
                    </td>
                </tr>
            <?php endforeach; ?>
            <?php if (empty($this->bonds)): ?>
                <tr>
                    <td colspan="3" class="text-center">Nenhum vínculo encontrado.</td>
                </tr>
            <?php endif; ?>
        </tbody>
    </table>
</div>

<script src="/js/application/vinculos/index.js"></script>
