<div class="container">
    <h1 class="text-center mb-4">Informações dos Veículos</h1>
    <div class="text-right mb-3">
        <button class="btn btn-success" onclick="window.location.href='/vehicles/save'">Criar Novo Veículo</button>
    </div>
    <table class="table table-bordered">
        <thead class="thead-dark">
            <tr>
                <th>Placa</th>
                <th>Modelo</th>
                <th>Marca</th>
                <th>Ano</th>
                <th>Cor</th>
                <th>Motoristas</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->vehicles as $vehicle): ?>
                    <tr>
                        <td><?php echo $vehicle['placa'] ?></td>
                        <td><?php echo $vehicle['modelo'] ?></td>
                        <td><?php echo $vehicle['marca'] ?></td>
                        <td><?php echo $vehicle['ano'] ?></td>
                        <td><?php echo $vehicle['cor'] ?></td>
                        <td><?php echo implode('<br>', $vehicle['drivers']) ?></td>
                        <td class="d-flex justify-content-center">
                            <button class="btn btn-primary btn-sm mr-2" onclick="window.location.href='/vehicles/save?placa=<?php echo $vehicle['placa'] ?>'">Editar</button>
                            <button class="btn btn-danger btn-sm mr-2 delete" href="/vehicles/delete" data-placa="<?php echo $vehicle['placa'] ?>">Deletar</button>
                        </td>
                    </tr>
            <?php endforeach; ?>
            <?php if (empty($this->vehicles)): ?>
                <tr>
                    <td colspan="8" class="text-center">Nenhum vínculo encontrado.</td>
                </tr>
            <?php endif; ?>
        </tbody>
    </table>
</div>


<script src="/js/application/vehicles/index.js"></script>