<div class="container">
    <h1 class="text-center mb-4">Informações dos Veículos</h1>
    <div class="text-right mb-3">
        <button class="btn btn-success" onclick="window.location.href='/vehicles/save'">Criar Novo Veículo</button>
    </div>
    <table class="table table-bordered">
        <thead class="thead-dark">
            <tr>
                <th>Placa</th>
                <th>Modelo</th>
                <th>Marca</th>
                <th>Ano</th>
                <th>Cor</th>
                <th>Motoristas</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            <?php
            if(empty($this->vehicles)) :
                echo '<tr><td colspan="6" class="text-center">Nenhum veículo cadastrado</td></tr>';
            else:
                foreach ($this->vehicles as $vehicle): ?>
                    <tr>
                        <td><?= $vehicle['placa'] ?></td>
                        <td><?= $vehicle['modelo'] ?></td>
                        <td><?= $vehicle['marca'] ?></td>
                        <td><?= $vehicle['ano'] ?></td>
                        <td><?= $vehicle['cor'] ?></td>
                        <td><?= implode('<br>', $vehicle['drivers']) ?></td>
                        <td class="d-flex justify-content-center">
                            <button class="btn btn-primary btn-sm mr-2" onclick="window.location.href='/vehicles/save/placa/<?= $vehicle['placa'] ?>'">Editar</button>
                            <button class="btn btn-danger btn-sm mr-2 delete" href="/vehicles/delete" data-placa="<?= $vehicle['placa'] ?>">Deletar</button>
                            <button class="btn btn-secondary btn-sm mr-2 vincular" href="/vinculos/placa/<?php echo $vehicle['placa']?>">Vincular Motorista</button>
                        </td>
                    </tr>
            <?php
                endforeach;
            endif;
            ?>
        </tbody>
    </table>
</div>

<script>
    $(document).ready(function() {
        $('.delete').on('click', function(event) {
            event.preventDefault();
            $.ajax({
                url: $(this).attr('href'),
                method: 'POST',
                data: {
                    placa: $(this).data('placa')
                },
                success: function(response) {
                    if (response.success) {
                        alert('Veículo deletado com sucesso!');
                    } else {
                        alert('Erro ao deletar veículo: ' + response.message);
                    }
                },
                error: function(data) {
                    console.log(data)
                    alert('Erro ao processar a solicitação.');
                }
            });
        });
    });
</script>