<div class="container">
    <h1 class="text-center mb-4">Informações dos Motoristas</h1>
    <div class="text-right mb-3">
        <button class="btn btn-success" onclick="window.location.href='/drivers/create'">Criar Novo Motorista</button>
    </div>
    <table class="table table-bordered">
        <thead class="thead-dark">
            <tr>
                <th>CPF</th>
                <th>RG</th>
                <th>Nome</th>
                <th>Telefone</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->drivers as $driver): ?>
                <tr>
                    <td><?= $driver['cpf'] ?></td>
                    <td><?= $driver['rg'] ?></td>
                    <td><?= $driver['nome'] ?></td>
                    <td><?= $driver['telefone'] ?></td>
                    <td class="d-flex justify-content-center">
                        <button class="btn btn-primary btn-sm mr-2" onclick="window.location.href='/drivers/edit/<?= $driver['cpf'] ?>'">Editar</button>
                        <button class="btn btn-danger btn-sm mr-2" onclick="window.location.href='/drivers/delete/<?= $driver['cpf'] ?>'">Deletar</button>
                        <button class="btn btn-secondary btn-sm mr-2" onclick="window.location.href='/drivers/drivers/<?= $driver['cpf'] ?>'">Veículos</button>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>