<div class="container">
    <h1 class="text-center mb-4">Informações dos Motoristas</h1>
    <div class="text-right mb-3">
        <button class="btn btn-success" onclick="window.location.href='/drivers/save'">Criar Novo Motorista</button>
    </div>
    <table class="table table-bordered">
        <thead class="thead-dark">
            <tr>
                <th>CPF</th>
                <th>RG</th>
                <th>Nome</th>
                <th>Telefone</th>
                <th>Veículos</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->drivers as $driver): ?>
                <tr>
                    <td><?= $driver['cpf'] ?></td>
                    <td><?= $driver['rg'] ?></td>
                    <td><?= $driver['nome'] ?></td>
                    <td><?= $driver['telefone'] ?></td>
                    <td><?= implode('<br>', $driver['vehicles']) ?></td>
                    <td class="d-flex justify-content-center">
                        <button class="btn btn-primary btn-sm mr-2" onclick="window.location.href='/drivers/save?cpf=<?= $driver['cpf'] ?>'">Editar</button>
                        <button class="btn btn-danger btn-sm mr-2 delete" data-cpf="<?= $driver['cpf'] ?>" href="/drivers/delete">Deletar</button>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>

<script src="/js/application/drivers/index.js"></script>