<html lang="pt-br">
    <head>
        <meta charset="UTF-8">
        <title>Trafegus - Teste Técnico</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    </head>
    <body style="height: 100vh" class="text-center">
        <div class="sticky-top" style="height: 10vh;">
            <nav class="navbar navbar-expand-lg navbar-light">
                <a class="navbar-brand" href="/">
                    <img src="https://trafegus.rootcore.com.br/wp-content/uploads/2024/07/logo-trafegus-dark-2.svg#2" alt="logo-trafegus-white" width="200px" height="40px">
                </a>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <a class="" href="/drivers">
                        <button class="btn btn-primary">Motoristas</button>
                    </a>
                    <a class="" href="/vehicles">
                        <button class="btn btn-primary">Veículos</button>
                    </a>
                </div>
            </nav>
        </div>

        <div class="bg-light" style="width: 100vw; height: 90vh">
            <?= $this->content; ?>
        </div>

        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    </body>
</html>
