<html lang="pt-br">
    <head>
        <meta charset="UTF-8">
        <title>Trafegus - Teste Técnico</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    </head>
    <body style="height: 100vh" class="text-center">
        <div class="sticky-top" style="height: 10vh;">
            <nav class="navbar navbar-expand-lg navbar-light">
                <div class="container-fluid">
                    <a class="navbar-brand" href="/">
                        <img src="https://trafegus.rootcore.com.br/wp-content/uploads/2024/07/logo-trafegus-dark-2.svg#2" alt="logo-trafegus-white" width="200px" height="40px">
                    </a>
                    <div class="collapse navbar-collapse m-auto right" id="navbarNav">
                        <div class="nav-item">
                            <a class="nav-link me-3" href="/drivers">
                                Motoristas
                            </a>
                        </div>
                        <div class="nav-item">
                            <a class="nav-link" href="/vehicles">
                                Veículos
                            </a>
                        </div>
                        <div class="nav-item">
                            <a class="nav-link" href="/vinculos">
                                Vínculos
                            </a>
                        </div>
                    </div>
                </div>
            </nav>
        </div>

        <div class="bg-light" style="width: 100vw; height: 90vh">
            <?= $this->content; ?>
        </div>

        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    </body>
</html>
