<html lang="pt-br">
    <head>
        <meta charset="UTF-8">
        <title>Trafegus - Teste Técnico</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    </head>
    <body style="height: 100vh" class="text-center">
        <div class="sticky-top">
            <nav class="navbar navbar-expand-lg navbar-light">
                <a class="navbar-brand">
                    <img src="https://trafegus.rootcore.com.br/wp-content/uploads/2024/07/logo-trafegus-dark-2.svg#2" alt="logo-trafegus-white" width="200px" height="40px">
                </a>
            </nav>
        </div>

        <div class="bg-light" style="width: 100vw; height: 100%">
            <?= $this->content; ?>
        </div>

    </body>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
</html>
